// Code generated by go generate gen.go; DO NOT EDIT.
//go:generate go run gen.go
package hapr

import (
	"golang.org/x/net/html"
	"golang.org/x/net/html/atom"
)

func A(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.A, attrs, children...)
}

func Abbr(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Abbr, attrs, children...)
}

func Address(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Address, attrs, children...)
}

func Area(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Area, attrs, children...)
}

func Article(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Article, attrs, children...)
}

func Aside(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Aside, attrs, children...)
}

func Audio(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Audio, attrs, children...)
}

func B(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.B, attrs, children...)
}

func Base(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Base, attrs, children...)
}

func Bdi(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Bdi, attrs, children...)
}

func Bdo(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Bdo, attrs, children...)
}

func Blockquote(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Blockquote, attrs, children...)
}

func Body(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Body, attrs, children...)
}

func Br(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Br, attrs, children...)
}

func Button(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Button, attrs, children...)
}

func Canvas(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Canvas, attrs, children...)
}

func Caption(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Caption, attrs, children...)
}

func Cite(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Cite, attrs, children...)
}

func Code(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Code, attrs, children...)
}

func Col(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Col, attrs, children...)
}

func Colgroup(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Colgroup, attrs, children...)
}

func Command(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Command, attrs, children...)
}

func Data(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Data, attrs, children...)
}

func Datalist(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Datalist, attrs, children...)
}

func Dd(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Dd, attrs, children...)
}

func Del(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Del, attrs, children...)
}

func Details(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Details, attrs, children...)
}

func Dfn(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Dfn, attrs, children...)
}

func Dialog(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Dialog, attrs, children...)
}

func Div(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Div, attrs, children...)
}

func Dl(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Dl, attrs, children...)
}

func Dt(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Dt, attrs, children...)
}

func Em(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Em, attrs, children...)
}

func Embed(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Embed, attrs, children...)
}

func Fieldset(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Fieldset, attrs, children...)
}

func Figcaption(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Figcaption, attrs, children...)
}

func Figure(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Figure, attrs, children...)
}

func Footer(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Footer, attrs, children...)
}

func Form(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Form, attrs, children...)
}

func H1(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.H1, attrs, children...)
}

func H2(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.H2, attrs, children...)
}

func H3(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.H3, attrs, children...)
}

func H4(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.H4, attrs, children...)
}

func H5(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.H5, attrs, children...)
}

func H6(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.H6, attrs, children...)
}

func Head(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Head, attrs, children...)
}

func Header(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Header, attrs, children...)
}

func Hgroup(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Hgroup, attrs, children...)
}

func Hr(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Hr, attrs, children...)
}

func Html(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Html, attrs, children...)
}

func I(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.I, attrs, children...)
}

func Iframe(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Iframe, attrs, children...)
}

func Img(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Img, attrs, children...)
}

func Input(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Input, attrs, children...)
}

func Ins(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Ins, attrs, children...)
}

func Kbd(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Kbd, attrs, children...)
}

func Keygen(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Keygen, attrs, children...)
}

func Label(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Label, attrs, children...)
}

func Legend(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Legend, attrs, children...)
}

func Li(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Li, attrs, children...)
}

func Link(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Link, attrs, children...)
}

func Main(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Main, attrs, children...)
}

func Map(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Map, attrs, children...)
}

func Mark(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Mark, attrs, children...)
}

func Menu(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Menu, attrs, children...)
}

func Menuitem(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Menuitem, attrs, children...)
}

func Meta(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Meta, attrs, children...)
}

func Meter(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Meter, attrs, children...)
}

func Nav(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Nav, attrs, children...)
}

func Noscript(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Noscript, attrs, children...)
}

func Object(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Object, attrs, children...)
}

func Ol(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Ol, attrs, children...)
}

func Optgroup(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Optgroup, attrs, children...)
}

func Option(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Option, attrs, children...)
}

func Output(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Output, attrs, children...)
}

func P(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.P, attrs, children...)
}

func Param(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Param, attrs, children...)
}

func Picture(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Picture, attrs, children...)
}

func Pre(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Pre, attrs, children...)
}

func Progress(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Progress, attrs, children...)
}

func Q(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Q, attrs, children...)
}

func Rp(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Rp, attrs, children...)
}

func Rt(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Rt, attrs, children...)
}

func Ruby(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Ruby, attrs, children...)
}

func S(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.S, attrs, children...)
}

func Samp(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Samp, attrs, children...)
}

func Script(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Script, attrs, children...)
}

func Section(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Section, attrs, children...)
}

func Select(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Select, attrs, children...)
}

func Slot(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Slot, attrs, children...)
}

func Small(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Small, attrs, children...)
}

func Source(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Source, attrs, children...)
}

func Span(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Span, attrs, children...)
}

func Strong(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Strong, attrs, children...)
}

func Style(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Style, attrs, children...)
}

func Sub(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Sub, attrs, children...)
}

func Summary(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Summary, attrs, children...)
}

func Sup(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Sup, attrs, children...)
}

func Table(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Table, attrs, children...)
}

func Tbody(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Tbody, attrs, children...)
}

func Td(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Td, attrs, children...)
}

func Template(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Template, attrs, children...)
}

func Textarea(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Textarea, attrs, children...)
}

func Tfoot(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Tfoot, attrs, children...)
}

func Th(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Th, attrs, children...)
}

func Thead(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Thead, attrs, children...)
}

func Time(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Time, attrs, children...)
}

func Title(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Title, attrs, children...)
}

func Tr(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Tr, attrs, children...)
}

func Track(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Track, attrs, children...)
}

func U(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.U, attrs, children...)
}

func Ul(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Ul, attrs, children...)
}

func Var(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Var, attrs, children...)
}

func Video(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Video, attrs, children...)
}

func Wbr(attrs []html.Attribute, children ...*html.Node) *html.Node {
	return New(atom.Wbr, attrs, children...)
}
